## Accessing changing specific elements of rows and columns

In [6]:
import numpy as np

In [24]:
lst = [1,2,3]
lst
type(lst)

list

In [25]:
lst2 = [[1,2,3],[4,5,6]]
lst2

[[1, 2, 3], [4, 5, 6]]

In [26]:
a = np.array(lst)
a
type(a)

numpy.ndarray

In [27]:
b = np.array([[9.0,8.0,7.0,8],[6.0,5.0,4.0,4]])
print(b)

[[9. 8. 7. 8.]
 [6. 5. 4. 4.]]


In [28]:
# Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [29]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 4)


In [30]:
a = np.array([1,2,3], dtype='int16')

In [31]:
# Get type
print(a.dtype)
print(b.dtype)

int16
float64


In [32]:
# Get size
print(a.size)
print(b.size)

3
8


In [33]:
# Get itemsize gives size in bytes
print(a.itemsize) # 2 bytes means 2*8 bits
print(b.itemsize)

2
8


In [34]:
# get totalsize of array
# a.size gives total number of items and a.itemsize gives array elements(items) size in byte
# so for a, a.size is 3, and a.itemsize is 2 Bytes so 3*6 = 2
print(a.size * a.itemsize)
print(b.size*b.itemsize)
print(b.nbytes)

6
64
64


In [104]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[18,19,110,111,112,113,114]], 'int16')
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12  13  14]
 [ 18  19 110 111 112 113 114]]


In [10]:
z=[[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[18,19,110,111,112,113,114]]
print(z)

[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14], [18, 19, 110, 111, 112, 113, 114]]


In [17]:
# getting a specific element (r,c)
a[1,5]

13

In [26]:
# getting a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
# getting specific column
a[:,1]

array([ 2,  9, 19])

In [57]:
# getting specific range [row, startindes:endindex:stepsize]
a[1, 1:6:2]
#a[1, 1:-1:2]

array([ 9, 11, 13], dtype=int16)

In [65]:
#changing specific element
a[1,1] = 6 # 9 changed to 6
print(a)
# 0=row, startindes:endindex:stepsize
a[0, 1:6:2] = [1,1,1]
a

[[  1   1   3   1   5   1   7]
 [  8   6  10   1  12   1  14]
 [ 18  19 110 111 112 113 114]]


array([[  1,   1,   3,   1,   5,   1,   7],
       [  8,   6,  10,   1,  12,   1,  14],
       [ 18,  19, 110, 111, 112, 113, 114]], dtype=int16)

In [66]:
# changing an entire column
a[:,1]=[3,4,5]
print(a)

[[  1   3   3   1   5   1   7]
 [  8   4  10   1  12   1  14]
 [ 18   5 110 111 112 113 114]]


### 3-d example

In [140]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print('shape of an array',b.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape of an array (2, 2, 2)


In [89]:
# getting specific element (work outside in)
b[0,1,1] # 0=list 0, 1=row 1 of list 0 and 1 = column 1 of list 0

b[:,1,:] # : = all list, 1 = row 1 and : = all column

array([[3, 4],
       [7, 8]])

In [90]:
# replace
b[:,1,:] = [5,5]
b

array([[[1, 2],
        [5, 5]],

       [[5, 6],
        [5, 5]]])

In [93]:
b[:,:,1]= [[11,12],[13,14]]
b


array([[[ 1, 11],
        [ 5, 12]],

       [[ 5, 13],
        [ 5, 14]]])

### Initializing different types of arrays

In [97]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [99]:
np.ones((4,2,3),'int8')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int8)

In [102]:
#full
np.full((2,2),9)

array([[9, 9],
       [9, 9]])

In [106]:
# any other number full_like
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]], dtype=int16)

In [113]:
# random decimal number
np.random.rand(2,2,2,1)

array([[[[0.53142541],
         [0.63242958]],

        [[0.54980223],
         [0.31690883]]],


       [[[0.86735721],
         [0.54496774]],

        [[0.2317305 ],
         [0.49192418]]]])

In [115]:
np.random.random_sample(a.shape)

array([[0.86265164, 0.19428411, 0.92673277, 0.50660006, 0.4701846 ,
        0.98689976, 0.2618752 ],
       [0.28243974, 0.0976482 , 0.01185253, 0.22423304, 0.94444899,
        0.70435347, 0.31657897],
       [0.74974248, 0.8109687 , 0.84762694, 0.29214177, 0.72155729,
        0.85216913, 0.62336843]])

In [116]:
np.random.rand(4,2)

array([[0.63630877, 0.34363984],
       [0.11116909, 0.01006173],
       [0.05059012, 0.8421669 ],
       [0.20734454, 0.74668932]])

In [123]:
# random integer values
np.random.randint(7, size=(2,3,3))

array([[[5, 5, 0],
        [6, 2, 1],
        [5, 4, 0]],

       [[3, 5, 3],
        [3, 1, 0],
        [5, 2, 0]]])

In [153]:
# identity matrix
ident=np.identity(2)
ident

array([[1., 0.],
       [0., 1.]])

In [141]:
arr = np.array([[1,2,3]])
# In numpy the axis with index 0 refers to the rows, while the axis with index 1 refers to the columns.
r1 = np.repeat(arr,3, axis=0) 
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [149]:
np.array([[1,2,3],[3,3,3]])

array([[1, 2, 3],
       [3, 3, 3]])

In [185]:
practice = np.ones((5,5),'int8')
practice[1:4,1:4] = 0
practice[2,2] = 9
practice

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

### Careful when copying arrays

In [186]:
a = np.array([1,2,3])
b = a # what it does is a and b points to the same list object in memory, so when value of b is changed value of a is also changed lets see
b[0] = 55
print(b)
print(a)
# here value of a is changed when only changing the value of b, because a and b point to the same list object in memory

[55  2  3]
[55  2  3]


In [187]:
# how to copy array in numpy
a = np.array([1,2,3])
b = a.copy()
b[0]=44
print(b)
print(a)

[44  2  3]
[1 2 3]


## Mathematics

In [27]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
a+2
a

array([1, 2, 3, 4])

In [13]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [21]:
a*2

array([ 6,  8, 10, 12])

In [15]:
a-2

array([-1,  0,  1,  2])

In [24]:
#a+=2
a

array([3, 4, 5, 6])

In [18]:
a-2

array([3, 4, 5, 6])

In [25]:
b = np.array([1,0,1,0])

In [28]:
a+b

array([2, 2, 4, 4])

In [41]:
# take sin and cos
np.sin(a)
a
np.cos(a)
a

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [42]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),4)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]


In [46]:
# matrix multiplication
mul = np.matmul(a,b) # returns 2*2 matrix, columns and rows of matrix that are being multiplied should be equal.
print(mul)

[[12. 12.]
 [12. 12.]]


In [ ]:
# reference docs https://numpy.org/doc/stable/reference/routines.math.html

In [54]:
# find determinant of matrix
c = np.identity(3)
np.linalg.det(c)

1.0

In [55]:
# reference docs https://numpy.org/doc/stable/reference/routines.linalg.html
# Determinant
# trace
# singular vector decomposition
# eigenvalues
# matrix norm
# inverse

### Statistics

In [3]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.min(stats)

1

In [58]:
np.max(stats)

6

A 2-dimensional array has two corresponding axes: the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1).

Many operation can take place along one of these axes. For example, we can sum each row of an array, in which case we operate along columns, or axis 1:

>>>
>>> x = np.arange(12).reshape((3,4))

>>> x
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

>>> x.sum(axis=1)
array([ 6, 22, 38])

In [5]:
stats.sum(axis=1) # performing sum through row by passing axis=1

array([ 6, 15])

In [6]:
stats.sum(axis=0)

array([5, 7, 9])

In [64]:
np.min(stats, axis=0) # performs the operation across the columns, while keeping the rows intact

array([1, 2, 3])

In [65]:
np.min(stats, axis=1) # performs the operation across the rows, while keeping the column intact

array([1, 4])

In [66]:
np.max(stats, axis=1)

array([3, 6])

In [67]:
np.max(stats, axis=0)

array([4, 5, 6])

In [68]:
np.sum(stats)

21

In [70]:
np.sum(stats,axis=0)

array([5, 7, 9])

### Reorganizing and reshaping

In [7]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

###### Vertical Stack

In [2]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

##### Horizontal Stack

In [5]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
Load data from file

We use genfromtxt method to import txt file

In [13]:
filedata = np.genfromtxt('DataForMiscellaneous.txt', delimiter=',')
print(filedata)
filedata = filedata.astype('int32')  # converting float into int32
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   5.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  13. 999.  11.   2.   3.  75.   8.   3.   2.   8.   7.
    1.  26.  30.   1.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   5   4   3   4   5   6   7   0  11  12]
 [  1  22  33  13 999  11   2   3  75   8   3   2   8   7   1  26  30   1]]


### Advance indexing

##### Boolean masking and advance indexing

In [14]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False, False, False]])

In [16]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  75], dtype=int32)

#### Indexing with a list in numpy
Indexing by passing a list inside numpy array

In [20]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] # passing index of the list and return the value at the index

array([2, 3, 9])

##### Boolean masking and advanced indexing through rows

Getting any values in the columns which are greater than 50

In [21]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False, False, False])

In [27]:
# boolean masking the columns which values are greater than 50
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [29]:
# boolean masking values which are greater than 50 and less than 100
((filedata>50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False, False, False]])

In [30]:
# boolean masking values which are not greater than 50 and less than 100
(~((filedata>50) & (filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

##### Advance indexing

In [8]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
# printing 11, 12, 16, 17 
print(a[2:4,0:2])

[[11 12]
 [16 17]]


In [13]:
# indexing 2,8,14,20
print(a[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


In [23]:
# indexing 4,5,24,25,29,30
print(a[[0,4,5],3:5])

[[ 4  5]
 [24 25]
 [29 30]]
